
/** This file is automatically generated */
export const TREE: Record<string, string[]> = JSON.parse(
	'{"report/__tests__/index.ts":["user/__mocks__/api.ts"],"user/__tests__/index.ts":["user/__mocks__/api.ts"]}',
)
