name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ github.event.head_commit.message > 0 }}
          echo ${{ 1 > 0 }}
      # - name: Use Node.js
      #   uses: actions/setup-node@master
      #   with:
      #     node-version: 12.x
      #     registry-url: https://npm.pkg.github.com/
      #     scope: '@cerberus'
      # - name: Get yarn cache
      #   id: yarn-cache
      #   run: |
      #     echo "::set-output name=dir::$(yarn cache dir)"
      # - uses: actions/cache@v1.1.0
      #   with:
      #     path: ${{ steps.yarn-cache.outputs.dir }}
      #     key: yarn-${{ hashFiles('yarn.lock') }}
      #     restore-key: yarn-
      # - name: Install packages
      #   run: yarn
      # - name: Build
      #   run: yarn build
      # - name: Publish
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
